config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, {presence: true, length: {maximum: 140}}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path, notice: "投稿しました！"
      else
        render :new
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, notice: "投稿内容を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice:"投稿を削除しました！"
  end

  def confirm
    @post = Post.new(post_params)
    render :new if @post.invalid?
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header clearfix">
      <%= image_tag 'party_cracker.jpeg', class: 'head_img' %>
    <nav>
      <ul class="top_menu clearfix">
        <%= link_to "投稿一覧画面にもどる", posts_path, class:'top_menu' %>
      </ul>
    </nav>
  </header>
    <div class="container">
      <%= yield %>
    </div>

  <footer>
　　<ul class="footer-menu">
    <li>home ｜</li>
    <li>about ｜</li>
    <li>service ｜</li>
    <li>Contact Us</li>
  </ul>
    <p>© All rights reserved by webcampnavi.</p>
  </footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="post_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "投稿一覧画面にもどる", posts_path %>

app/views/posts/confirm.html.erb
<h3>以下の内容で、投稿する。</h3>

<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @post.content %></p>
  <%= form.submit  "登録する" %>

  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/posts/edit.html.erb
  <h2>編集する</h2>

  <%= render 'form' %>

app/views/posts/index.html.erb
<h1 width="100%">投稿一覧</h1>

<p><%= notice %></p>

<table>
  <tr>
    <th>内容</th>
  </tr>

<% @posts.each do |post| %>
  <tr class="content_all">
    <td width="20%"><%= l post.created_at %></td>
    <td width="50%"><%= post.content %></td>
    <td width="10%"><%= link_to '投稿確認する', post_path(post.id) %></td>
    <td width="10%"><%= link_to "編集する", edit_post_path(post.id), data: { confirm: '本当に編集していいですか？' } %></td>
    <td width="10%"><%= link_to '削除する', post_path(post.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>

<%= link_to '新しく投稿する', new_post_path %>

app/views/posts/new.html.erb
  <h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/posts/show.html.erb
<h1>投稿確認画面</h1>
<p>タイトル: <%= @post.created_at %></p>
<p>内容: <%= @post.content %></p>